/* Copyright (c) 2015, Oracle and/or its affiliates. All rights reserved. */

/******************************************************************************
 *
 * You may not use the identified files except in compliance with the Apache
 * License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * NAME
 *   config.js
 *
 * DESCRIPTION
 *   The configuration file for the listener.
 *
 *****************************************************************************/

module.exports = {
    port: 7000,
    useCache: false,
	redis: {
		server: "localhost",
		port: 6379,
		options: {}
	},
    staticFileRepos: [
        {
            alias: "/i/",
            path: "/u01/oracle/apex/images"
        }
    ],
    dads: {
        "ords-s": {
            user: "polar",
            password: "polardev2#",
            connectString: "m1-erp-appdev2.m1.baidu.com:8541/PLDEV2",
            poolMax: 44,
            poolMin: 2,
            poolIncrement: 5,
            poolTimeout: 4,
            requestValidationFunction: "wwv_flow_epg_include_modules.authorize",
            defaultPage: "ords-s"
        },
		/*"ords-m": {
            user: "apps",
            password: "apps",
            connectString: "m1-erp-devdb07.m1:1591/DEV7",
            poolMax: 44,
            poolMin: 2,
            poolIncrement: 1,
            poolTimeout: 4,
            requestValidationFunction: "wwv_flow_epg_include_modules.authorize",
            defaultPage: "ords-m"
		},*/
		"ords-l": {
            user: "hr",
            password: "oracle",
            connectString: "localhost:1521/pdb1",
            poolMax: 44,
            poolMin: 2,
            poolIncrement: 5,
            poolTimeout: 4,
            requestValidationFunction: "wwv_flow_epg_include_modules.authorize",
            defaultPage: "ords-l"
		}
    },
    tempParamMappings: {
    	"apex_authentication.logout" : {},
        "wwv_flow.accept" : {
            p_arg_names: "wwv_flow_global.vc_arr2",
            p_arg_checksums: "wwv_flow_global.vc_arr2",
			p_arg_values: "wwv_flow_global.vc_arr2",
			p_accept_processing: "wwv_flow_global.vc_arr2",
            f01: "wwv_flow_global.vc_arr2",
            f02: "wwv_flow_global.vc_arr2",
            f03: "wwv_flow_global.vc_arr2",
            f04: "wwv_flow_global.vc_arr2",
            f05: "wwv_flow_global.vc_arr2",
            f06: "wwv_flow_global.vc_arr2",
            f07: "wwv_flow_global.vc_arr2",
            f08: "wwv_flow_global.vc_arr2",
            f09: "wwv_flow_global.vc_arr2",
            f10: "wwv_flow_global.vc_arr2",
            f11: "wwv_flow_global.vc_arr2",
            f12: "wwv_flow_global.vc_arr2",
            f13: "wwv_flow_global.vc_arr2",
            f14: "wwv_flow_global.vc_arr2",
            f15: "wwv_flow_global.vc_arr2",
            f16: "wwv_flow_global.vc_arr2",
            f17: "wwv_flow_global.vc_arr2",
            f18: "wwv_flow_global.vc_arr2",
            f19: "wwv_flow_global.vc_arr2",
            f20: "wwv_flow_global.vc_arr2",
			f21: "wwv_flow_global.vc_arr2",
            f22: "wwv_flow_global.vc_arr2",
            f23: "wwv_flow_global.vc_arr2",
            f24: "wwv_flow_global.vc_arr2",
            f25: "wwv_flow_global.vc_arr2",
            f26: "wwv_flow_global.vc_arr2",
            f27: "wwv_flow_global.vc_arr2",
            f28: "wwv_flow_global.vc_arr2",
            f29: "wwv_flow_global.vc_arr2",
            f30: "wwv_flow_global.vc_arr2",
            f31: "wwv_flow_global.vc_arr2",
            f32: "wwv_flow_global.vc_arr2",
            f33: "wwv_flow_global.vc_arr2",
            f34: "wwv_flow_global.vc_arr2",
            f35: "wwv_flow_global.vc_arr2",
            f36: "wwv_flow_global.vc_arr2",
            f37: "wwv_flow_global.vc_arr2",
            f38: "wwv_flow_global.vc_arr2",
            f39: "wwv_flow_global.vc_arr2",
            f40: "wwv_flow_global.vc_arr2",
            f41: "wwv_flow_global.vc_arr2",
            f42: "wwv_flow_global.vc_arr2",
            f43: "wwv_flow_global.vc_arr2",
            f44: "wwv_flow_global.vc_arr2",
            f45: "wwv_flow_global.vc_arr2",
            f46: "wwv_flow_global.vc_arr2",
            f47: "wwv_flow_global.vc_arr2",
            f48: "wwv_flow_global.vc_arr2",
            f49: "wwv_flow_global.vc_arr2",
            f50: "wwv_flow_global.vc_arr2",
			p_v01: "wwv_flow_global.vc_arr2",
			p_v02: "wwv_flow_global.vc_arr2",
			p_v03: "wwv_flow_global.vc_arr2",
			p_v04: "wwv_flow_global.vc_arr2",
			p_v05: "wwv_flow_global.vc_arr2",
			p_v06: "wwv_flow_global.vc_arr2",
			p_v07: "wwv_flow_global.vc_arr2",
			p_v08: "wwv_flow_global.vc_arr2",
			p_v09: "wwv_flow_global.vc_arr2",
			p_v10: "wwv_flow_global.vc_arr2",
			p_v11: "wwv_flow_global.vc_arr2",
			p_v12: "wwv_flow_global.vc_arr2",
			p_v13: "wwv_flow_global.vc_arr2",
			p_v14: "wwv_flow_global.vc_arr2",
			p_v15: "wwv_flow_global.vc_arr2",
			p_v16: "wwv_flow_global.vc_arr2",
			p_v17: "wwv_flow_global.vc_arr2",
			p_v18: "wwv_flow_global.vc_arr2",
			p_v19: "wwv_flow_global.vc_arr2",
			p_v20: "wwv_flow_global.vc_arr2",
			p_v21: "wwv_flow_global.vc_arr2",
			p_v22: "wwv_flow_global.vc_arr2",
			p_v23: "wwv_flow_global.vc_arr2",
			p_v24: "wwv_flow_global.vc_arr2",
			p_v25: "wwv_flow_global.vc_arr2",
			p_v26: "wwv_flow_global.vc_arr2",
			p_v27: "wwv_flow_global.vc_arr2",
			p_v28: "wwv_flow_global.vc_arr2",
			p_v29: "wwv_flow_global.vc_arr2",
			p_v30: "wwv_flow_global.vc_arr2",
			p_v31: "wwv_flow_global.vc_arr2",
			p_v32: "wwv_flow_global.vc_arr2",
			p_v33: "wwv_flow_global.vc_arr2",
			p_v34: "wwv_flow_global.vc_arr2",
			p_v35: "wwv_flow_global.vc_arr2",
			p_v36: "wwv_flow_global.vc_arr2",
			p_v37: "wwv_flow_global.vc_arr2",
			p_v38: "wwv_flow_global.vc_arr2",
			p_v39: "wwv_flow_global.vc_arr2",
			p_v40: "wwv_flow_global.vc_arr2",
			p_v41: "wwv_flow_global.vc_arr2",
			p_v42: "wwv_flow_global.vc_arr2",
			p_v43: "wwv_flow_global.vc_arr2",
			p_v44: "wwv_flow_global.vc_arr2",
			p_v45: "wwv_flow_global.vc_arr2",
			p_v46: "wwv_flow_global.vc_arr2",
			p_v47: "wwv_flow_global.vc_arr2",
			p_v48: "wwv_flow_global.vc_arr2",
			p_v49: "wwv_flow_global.vc_arr2",
			p_v50: "wwv_flow_global.vc_arr2",
			p_v51: "wwv_flow_global.vc_arr2",
			p_v52: "wwv_flow_global.vc_arr2",
			p_v53: "wwv_flow_global.vc_arr2",
			p_v54: "wwv_flow_global.vc_arr2",
			p_v55: "wwv_flow_global.vc_arr2",
			p_v56: "wwv_flow_global.vc_arr2",
			p_v57: "wwv_flow_global.vc_arr2",
			p_v58: "wwv_flow_global.vc_arr2",
			p_v59: "wwv_flow_global.vc_arr2",
			p_v60: "wwv_flow_global.vc_arr2",
			p_v61: "wwv_flow_global.vc_arr2",
			p_v62: "wwv_flow_global.vc_arr2",
			p_v63: "wwv_flow_global.vc_arr2",
			p_v64: "wwv_flow_global.vc_arr2",
			p_v65: "wwv_flow_global.vc_arr2",
			p_v66: "wwv_flow_global.vc_arr2",
			p_v67: "wwv_flow_global.vc_arr2",
			p_v68: "wwv_flow_global.vc_arr2",
			p_v69: "wwv_flow_global.vc_arr2",
			p_v70: "wwv_flow_global.vc_arr2",
			p_v71: "wwv_flow_global.vc_arr2",
			p_v72: "wwv_flow_global.vc_arr2",
			p_v73: "wwv_flow_global.vc_arr2",
			p_v74: "wwv_flow_global.vc_arr2",
			p_v75: "wwv_flow_global.vc_arr2",
			p_v76: "wwv_flow_global.vc_arr2",
			p_v77: "wwv_flow_global.vc_arr2",
			p_v78: "wwv_flow_global.vc_arr2",
			p_v79: "wwv_flow_global.vc_arr2",
			p_v80: "wwv_flow_global.vc_arr2",
			p_v81: "wwv_flow_global.vc_arr2",
			p_v82: "wwv_flow_global.vc_arr2",
			p_v83: "wwv_flow_global.vc_arr2",
			p_v84: "wwv_flow_global.vc_arr2",
			p_v85: "wwv_flow_global.vc_arr2",
			p_v86: "wwv_flow_global.vc_arr2",
			p_v87: "wwv_flow_global.vc_arr2",
			p_v88: "wwv_flow_global.vc_arr2",
			p_v89: "wwv_flow_global.vc_arr2",
			p_v90: "wwv_flow_global.vc_arr2",
			p_v91: "wwv_flow_global.vc_arr2",
			p_v92: "wwv_flow_global.vc_arr2",
			p_v93: "wwv_flow_global.vc_arr2",
			p_v94: "wwv_flow_global.vc_arr2",
			p_v95: "wwv_flow_global.vc_arr2",
			p_v96: "wwv_flow_global.vc_arr2",
			p_v97: "wwv_flow_global.vc_arr2",
			p_v98: "wwv_flow_global.vc_arr2",
			p_v99: "wwv_flow_global.vc_arr2",
			p_v100: "wwv_flow_global.vc_arr2",
			p_v101: "wwv_flow_global.vc_arr2",
			p_v102: "wwv_flow_global.vc_arr2",
			p_v103: "wwv_flow_global.vc_arr2",
			p_v104: "wwv_flow_global.vc_arr2",
			p_v105: "wwv_flow_global.vc_arr2",
			p_v106: "wwv_flow_global.vc_arr2",
			p_v107: "wwv_flow_global.vc_arr2",
			p_v108: "wwv_flow_global.vc_arr2",
			p_v109: "wwv_flow_global.vc_arr2",
			p_v110: "wwv_flow_global.vc_arr2",
			p_v111: "wwv_flow_global.vc_arr2",
			p_v112: "wwv_flow_global.vc_arr2",
			p_v113: "wwv_flow_global.vc_arr2",
			p_v114: "wwv_flow_global.vc_arr2",
			p_v115: "wwv_flow_global.vc_arr2",
			p_v116: "wwv_flow_global.vc_arr2",
			p_v117: "wwv_flow_global.vc_arr2",
			p_v118: "wwv_flow_global.vc_arr2",
			p_v119: "wwv_flow_global.vc_arr2",
			p_v120: "wwv_flow_global.vc_arr2",
			p_v121: "wwv_flow_global.vc_arr2",
			p_v122: "wwv_flow_global.vc_arr2",
			p_v123: "wwv_flow_global.vc_arr2",
			p_v124: "wwv_flow_global.vc_arr2",
			p_v125: "wwv_flow_global.vc_arr2",
			p_v126: "wwv_flow_global.vc_arr2",
			p_v127: "wwv_flow_global.vc_arr2",
			p_v128: "wwv_flow_global.vc_arr2",
			p_v129: "wwv_flow_global.vc_arr2",
			p_v130: "wwv_flow_global.vc_arr2",
			p_v131: "wwv_flow_global.vc_arr2",
			p_v132: "wwv_flow_global.vc_arr2",
			p_v133: "wwv_flow_global.vc_arr2",
			p_v134: "wwv_flow_global.vc_arr2",
			p_v135: "wwv_flow_global.vc_arr2",
			p_v136: "wwv_flow_global.vc_arr2",
			p_v137: "wwv_flow_global.vc_arr2",
			p_v138: "wwv_flow_global.vc_arr2",
			p_v139: "wwv_flow_global.vc_arr2",
			p_v140: "wwv_flow_global.vc_arr2",
			p_v141: "wwv_flow_global.vc_arr2",
			p_v142: "wwv_flow_global.vc_arr2",
			p_v143: "wwv_flow_global.vc_arr2",
			p_v144: "wwv_flow_global.vc_arr2",
			p_v145: "wwv_flow_global.vc_arr2",
			p_v146: "wwv_flow_global.vc_arr2",
			p_v147: "wwv_flow_global.vc_arr2",
			p_v148: "wwv_flow_global.vc_arr2",
			p_v149: "wwv_flow_global.vc_arr2",
			p_v150: "wwv_flow_global.vc_arr2",
			p_v151: "wwv_flow_global.vc_arr2",
			p_v152: "wwv_flow_global.vc_arr2",
			p_v153: "wwv_flow_global.vc_arr2",
			p_v154: "wwv_flow_global.vc_arr2",
			p_v155: "wwv_flow_global.vc_arr2",
			p_v156: "wwv_flow_global.vc_arr2",
			p_v157: "wwv_flow_global.vc_arr2",
			p_v158: "wwv_flow_global.vc_arr2",
			p_v159: "wwv_flow_global.vc_arr2",
			p_v160: "wwv_flow_global.vc_arr2",
			p_v161: "wwv_flow_global.vc_arr2",
			p_v162: "wwv_flow_global.vc_arr2",
			p_v163: "wwv_flow_global.vc_arr2",
			p_v164: "wwv_flow_global.vc_arr2",
			p_v165: "wwv_flow_global.vc_arr2",
			p_v166: "wwv_flow_global.vc_arr2",
			p_v167: "wwv_flow_global.vc_arr2",
			p_v168: "wwv_flow_global.vc_arr2",
			p_v169: "wwv_flow_global.vc_arr2",
			p_v170: "wwv_flow_global.vc_arr2",
			p_v171: "wwv_flow_global.vc_arr2",
			p_v172: "wwv_flow_global.vc_arr2",
			p_v173: "wwv_flow_global.vc_arr2",
			p_v174: "wwv_flow_global.vc_arr2",
			p_v175: "wwv_flow_global.vc_arr2",
			p_v176: "wwv_flow_global.vc_arr2",
			p_v177: "wwv_flow_global.vc_arr2",
			p_v178: "wwv_flow_global.vc_arr2",
			p_v179: "wwv_flow_global.vc_arr2",
			p_v180: "wwv_flow_global.vc_arr2",
			p_v181: "wwv_flow_global.vc_arr2",
			p_v182: "wwv_flow_global.vc_arr2",
			p_v183: "wwv_flow_global.vc_arr2",
			p_v184: "wwv_flow_global.vc_arr2",
			p_v185: "wwv_flow_global.vc_arr2",
			p_v186: "wwv_flow_global.vc_arr2",
			p_v187: "wwv_flow_global.vc_arr2",
			p_v188: "wwv_flow_global.vc_arr2",
			p_v189: "wwv_flow_global.vc_arr2",
			p_v190: "wwv_flow_global.vc_arr2",
			p_v191: "wwv_flow_global.vc_arr2",
			p_v192: "wwv_flow_global.vc_arr2",
			p_v193: "wwv_flow_global.vc_arr2",
			p_v194: "wwv_flow_global.vc_arr2",
			p_v195: "wwv_flow_global.vc_arr2",
			p_v196: "wwv_flow_global.vc_arr2",
			p_v197: "wwv_flow_global.vc_arr2",
			p_v198: "wwv_flow_global.vc_arr2",
			p_v199: "wwv_flow_global.vc_arr2",
			p_v200: "wwv_flow_global.vc_arr2",
			fcs: "wwv_flow_global.vc_arr2",
    		fmap: "wwv_flow_global.vc_arr2",
			fhdr: "wwv_flow_global.vc_arr2",
    		fcud: "wwv_flow_global.vc_arr2",
			frowid: "wwv_flow_global.vc_arr2",
			p_listener: "wwv_flow_global.vc_arr2",
			p_map1: "wwv_flow_global.vc_arr2",
			p_map2: "wwv_flow_global.vc_arr2",
			p_map3: "wwv_flow_global.vc_arr2"
        },
        "wwv_flow.show" : {
            p_arg_names: "wwv_flow_global.vc_arr2",
            p_arg_values: "wwv_flow_global.vc_arr2",
			p_clear_cache: "wwv_flow_global.vc_arr2",
            f01: "wwv_flow_global.vc_arr2",
            f02: "wwv_flow_global.vc_arr2",
            f03: "wwv_flow_global.vc_arr2",
            f04: "wwv_flow_global.vc_arr2",
            f05: "wwv_flow_global.vc_arr2",
            f06: "wwv_flow_global.vc_arr2",
            f07: "wwv_flow_global.vc_arr2",
            f08: "wwv_flow_global.vc_arr2",
            f09: "wwv_flow_global.vc_arr2",
            f10: "wwv_flow_global.vc_arr2",
            f11: "wwv_flow_global.vc_arr2",
            f12: "wwv_flow_global.vc_arr2",
            f13: "wwv_flow_global.vc_arr2",
            f14: "wwv_flow_global.vc_arr2",
            f15: "wwv_flow_global.vc_arr2",
            f16: "wwv_flow_global.vc_arr2",
            f17: "wwv_flow_global.vc_arr2",
            f18: "wwv_flow_global.vc_arr2",
            f19: "wwv_flow_global.vc_arr2",
            f20: "wwv_flow_global.vc_arr2"
        }
    }
};
